### ISSUE TITLE
Docker image recreation (seems) broken - yarn run build - Failed to compile.

### ISSUE THREAD

**Issue by AaronNGray** [datarhei/restreamer-ui#64]
I tried building the docker and got the error "Failed to compile.". On building on the command line on Ubuntu  I get :-
```
yarn run build
Creating an optimized production build...
Failed to compile.

[eslint] Invalid Options:
- Unknown options: extensions, resolvePluginsRelativeTo
- 'extensions' has been removed.
- 'resolvePluginsRelativeTo' has been removed.
```
The issue seems to be with eslint.

I am surprised that with a yarn.lock that this has broken !

I also had to do :-
```
sudo npm install -g corepack
corepack enable
yarn set version berry
```

react-scripts is notoriously bad now most node.js users have moved to things like [vite](https://www.npmjs.com/package/vite) now. I may well do this if there is not an easy obvious fix like a package.json `overrides`.

**Comment by AaronNGray** [comment]
This is issue https://github.com/facebook/create-react-app/issues/13618

**Comment by AaronNGray** [comment]
I am getting the following :-
```
/GitHub/datarhei/restreamer-ui$ sudo docker build .
[sudo] password for aaron: 
[+] Building 101.6s (12/15)                                      docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 604B                                       0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (li  0.0s
 => [internal] load metadata for docker.io/library/caddy:2.7.5-alpine      1.0s
 => [internal] load metadata for docker.io/library/node:21-alpine3.17      1.2s
 => [auth] library/caddy:pull token for registry-1.docker.io               0.0s
 => [auth] library/node:pull token for registry-1.docker.io                0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 194B                                          0.0s
 => [internal] load build context                                          0.3s
 => => transferring context: 16.00MB                                       0.2s
 => CACHED [stage-1 1/4] FROM docker.io/library/caddy:2.7.5-alpine@sha256  0.0s
 => [builder 1/4] FROM docker.io/library/node:21-alpine3.17@sha256:3c63a5  0.0s
 => CACHED [builder 2/4] COPY . /ui                                        0.0s
 => CACHED [builder 3/4] WORKDIR /ui                                       0.0s
 => ERROR [builder 4/4] RUN cd /ui &&  yarn set version berry &&  yarn   100.1s
------                                                                          
 > [builder 4/4] RUN cd /ui &&  yarn set version berry &&       yarn config set httpTimeout 600000 &&   yarn install &&         yarn run build:                 
0.523 (node:6) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.                                    
0.523 (Use `node --trace-deprecation ...` to show where the warning was created)
5.687 ➤ YN0000: You don't seem to have Corepack enabled; we'll have to rely on yarnPath instead
5.687 ➤ YN0000: Downloading https://repo.yarnpkg.com/4.5.0/packages/yarnpkg-cli/bin/yarn.js
6.593 ➤ YN0000: Saving the new release in .yarn/releases/yarn-4.5.0.cjs
6.646 ➤ YN0000: Done with warnings in 0s 960ms
7.164 ➤ YN0000: Successfully set httpTimeout to 600000
7.821 ➤ YN0087: Migrated your project to the latest Yarn version 🚀
7.821 
7.822 ➤ YN0000: · Yarn 4.5.0
7.839 ➤ YN0000: ┌ Resolution step
79.87 ➤ YN0001: │ RequestError
79.87     at ClientRequest.<anonymous> (/ui/.yarn/releases/yarn-4.5.0.cjs:147:14258)
79.87     at Object.onceWrapper (node:events:634:26)
79.87     at ClientRequest.emit (node:events:531:35)
79.87     at u.emit (/ui/.yarn/releases/yarn-4.5.0.cjs:142:14855)
79.87     at TLSSocket.socketErrorListener (node:_http_client:495:9)
79.87     at TLSSocket.emit (node:events:519:28)
79.87     at emitErrorNT (node:internal/streams/destroy:169:8)
79.87     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
79.87     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
79.87     at internalConnectMultiple (node:net:1114:18)
79.87     at internalConnectMultiple (node:net:1177:5)
79.87     at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
79.87     at listOnTimeout (node:internal/timers:575:11)
79.87     at process.processTimers (node:internal/timers:514:7)
79.88 ➤ YN0000: └ Completed in 1m 13s
79.88 ➤ YN0000: · Failed with errors in 1m 13s
------

 2 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 9)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 4)
Dockerfile:15
--------------------
  14 |     
  15 | >>> RUN cd /ui && \
  16 | >>> 	yarn set version berry && \
  17 | >>> 	yarn config set httpTimeout 600000 && \
  18 | >>>  	yarn install && \
  19 | >>>  	yarn run build
  20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /ui && \tyarn set version berry && \tyarn config set httpTimeout 600000 &&  \tyarn install &&  \tyarn run build" did not complete successfully: exit code: 1
```
